### ISSUE TITLE
user preferred nominations at voting stage

### ISSUE THREAD

**Issue by pupupu** [clamburger/vidya-gaem-awards#3]
after main nominations are in, there should be the ability to have multiple blank tiles where the voter can enter their own wildcards. this can either be from a large dropdown list of extra candidates, or a text field that can be semi-manually unified (spelling mistakes corrected, etc) with ineligible candidates filtered at a later stage

**Comment by pupupu** [comment]
![MOCKUP](https://f.cloud.github.com/assets/3760437/215355/1326fc2c-8480-11e2-8f11-3e050205043e.png)

here is a rough mockup, showing a site where the decision is made to allow 3 user nominees, as well as 5 official nominees for the category. the user can enter up to 3 of their own choices, and rank them the amongst the official nominees in the voting area.

**Comment by clamburger** [comment]
I don't think anybody cares about this anymore. Sorry puyo
